name: Deploy Docusaurus to GitHub Pages

on:
  push:
    branches: [main]
    paths:
      - 'website/**'
      - '.github/workflows/deploy-docs-simple.yml'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    name: Build Docusaurus
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: website
    steps:
      - uses: actions/checkout@v4

      - name: Calculate website content hash
        id: hash
        run: |
          # Calculate hash of all website source files (excluding node_modules and build)
          WEBSITE_HASH=$(find . -type f \( -name "*.ts" -o -name "*.tsx" -o -name "*.js" -o -name "*.jsx" -o -name "*.md" -o -name "*.mdx" -o -name "*.css" -o -name "*.json" \) ! -path "./node_modules/*" ! -path "./build/*" ! -path "./.docusaurus/*" -exec sha256sum {} \; | sort | sha256sum | cut -d' ' -f1)
          echo "website_hash=$WEBSITE_HASH" >> $GITHUB_OUTPUT
          echo "Website content hash: $WEBSITE_HASH"

      - name: Cache check
        id: cache-check
        uses: actions/cache@v4
        with:
          path: website/.build-hash
          key: website-build-${{ steps.hash.outputs.website_hash }}
          lookup-only: true

      - name: Check if build needed
        id: check-build
        run: |
          if [[ "${{ steps.cache-check.outputs.cache-hit }}" == "true" ]]; then
            echo "No changes detected in website content (hash: ${{ steps.hash.outputs.website_hash }})"
            echo "build_needed=false" >> $GITHUB_OUTPUT
          else
            echo "Changes detected, build needed"
            echo "build_needed=true" >> $GITHUB_OUTPUT
          fi

      - uses: actions/setup-node@v4
        if: steps.check-build.outputs.build_needed == 'true'
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: website/package-lock.json

      - name: Install dependencies
        if: steps.check-build.outputs.build_needed == 'true'
        run: npm ci

      - name: Restore cached build if exists
        if: steps.check-build.outputs.build_needed == 'false'
        uses: actions/cache/restore@v4
        with:
          path: website/build
          key: website-build-output-${{ steps.hash.outputs.website_hash }}
          fail-on-cache-miss: false

      - name: Build website
        if: steps.check-build.outputs.build_needed == 'true'
        run: npm run build

      - name: Save build hash
        if: steps.check-build.outputs.build_needed == 'true'
        run: |
          echo "${{ steps.hash.outputs.website_hash }}" > .build-hash
          
      - name: Cache build hash
        if: steps.check-build.outputs.build_needed == 'true'
        uses: actions/cache/save@v4
        with:
          path: website/.build-hash
          key: website-build-${{ steps.hash.outputs.website_hash }}

      - name: Cache build output
        if: steps.check-build.outputs.build_needed == 'true'
        uses: actions/cache/save@v4
        with:
          path: website/build
          key: website-build-output-${{ steps.hash.outputs.website_hash }}

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: website/build

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4